name: Verify

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  apk:
    name: Verify
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Download HMDM
        run: wget https://h-mdm.com/files/hmdm-1.1.2.aar -O android/hmdm.aar
      - name: Verify
        run: npm run verify
